name: Bandit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: petrucciani/bandit-check@master
        with:
          bandit_flags: "-r ./iot_spy/ -c .bandit.yml"
