name: Black

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Black
        uses: jpetrucciani/black-check@master
        with:
          path: "."
:w
